--- # MENUMAKER CONFIG FILE
-
    lunch: "12:30"
    dinner: "18:30"
    header: ""

    week_recommendations:
        lacteos: None
        carne: 1
        huevos: 2
        pescado: 1
        tubérculos:
        legumbres: 3
        frutos secos: 7
        verduras: 7
        pasta: 1
        cereales: None

    weekdays: 
        Monday:
            lunch: legumbres
            dinner: ensalada de rucola

        Tuesday:
            lunch: verduras
            dinner: verduras

        Wednesday:
            lunch: pastas
            dinner: pescados

        Thursday:
            lunch: arroces
            dinner: huevos, verduras

        Friday:
            lunch: legumbres
            dinner: verduras

        Saturday:
            lunch: carnes
            dinner: verduras

        Sunday:
            lunch: pastas
            dinner: verduras
